import 'dart:convert';
import 'dart:io';

import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../../core/database/daos/sport_export_dao.dart';
import '../../../core/modules/sport_game_state.dart';
import '../../modules/shared/sport_module_utils.dart';
import 'sport_export_service.dart';

class PdfExportService implements SportExportService {
  @override
  Future<File> exportGames(
    List<SportExportRecord> games, {
    required Directory tempDir,
  }) async {
    final timestamp = DateTime.now();
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        build: (_) => [
          pw.Text('SkorKeeper Export', style: const pw.TextStyle(fontSize: 24)),
          pw.SizedBox(height: 16),
          pw.TableHelper.fromTextArray(
            headers: const ['Sport', 'Matchup', 'Final'],
            data: [
              for (final game in games)
                [
                  SportModuleUtils.sportLabel(game.meta.sportType),
                  '${_state(game).awayTeam.name} at ${_state(game).homeTeam.name}',
                  '${_state(game).awayTeam.score}-${_state(game).homeTeam.score}',
                ],
            ],
          ),
        ],
        footer: (_) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text('Generated by SkorKeeper'),
        ),
      ),
    );
    for (final game in games) {
      final state = _state(game);
      doc.addPage(
        pw.MultiPage(
          build: (_) => [
            pw.Text(
              '${SportModuleUtils.sportLabel(game.meta.sportType)} • ${DateFormat.yMd().add_jm().format(DateTime.fromMillisecondsSinceEpoch(game.session.startedAt))}',
              style: const pw.TextStyle(fontSize: 18),
            ),
            pw.SizedBox(height: 8),
            pw.Text('${state.awayTeam.name} ${state.awayTeam.score} - ${state.homeTeam.score} ${state.homeTeam.name}'),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              headers: const ['Stat', 'Home', 'Away'],
              data: _statsRows(state),
            ),
            pw.SizedBox(height: 8),
            pw.Text('Notes'),
            pw.Text(game.notes?.content ?? state.notes ?? 'None'),
          ],
          footer: (_) => pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text('Generated by SkorKeeper'),
          ),
        ),
      );
    }
    final file = File(
      '${tempDir.path}\\SkorKeeper_Export_${DateFormat('yyyyMMdd_HHmmss').format(timestamp)}.pdf',
    );
    await file.writeAsBytes(await doc.save());
    return file;
  }

  SportGameState _state(SportExportRecord game) {
    return SportGameState.fromJson(
      jsonDecode(game.session.moduleStateJson) as Map<String, dynamic>,
    );
  }

  List<List<String>> _statsRows(SportGameState state) {
    final keys = <String>{
      ...state.homeTeam.stats.keys,
      ...state.awayTeam.stats.keys,
    };
    return [
      for (final key in keys)
        [
          key,
          '${state.homeTeam.stats[key] ?? ''}',
          '${state.awayTeam.stats[key] ?? ''}',
        ],
    ];
  }
}
